Add ability to set compression level or disable compression
mrrfv/open-android-backup pull request #36
Opened 2022-11-11 16:03 UTC by pvint

Based on the discussion in #32 I've added the ability to set compression level (1-9) or disable compression:

![image](https://user-images.githubusercontent.com/608740/201380969-e7e5e45a-a2b9-4744-841d-58ffe7f1662c.png)

Summary:
Set the compression level from 1-9, or set to 0 to disable compression and not run 7Zip at all. Tested and working for both backup and restore.

2022-11-11 23:15 UTC, mrrfv commented
Thank you so much! It's getting late where I live, so I'll review your PR tomorrow.

2022-11-13 21:40 UTC, mrrfv requested changes
I reviewed your changes a few days ago, and didn't realize that I have to submit the review for you to see my feedback :p

2022-11-13 21:40 UTC, mrrfv commented on backup.sh
> +  # If we're restoring from uncompressed backup, make sure at lease the Apps directory exists
```suggestion
  # If we're restoring from uncompressed backup, make sure at least the Apps directory exists
```

kinda nitpicking here

2022-11-13 21:40 UTC, mrrfv commented on backup.sh
> +    declare backup_archive="$archive_path/linux-android-backup-$(date +%m-%d-%Y-%H-%M-%S).7z"
in order to ensure compatibility with hooks, `backup_archive` should be defined regardless of whether the user's using compression or not.

https://github.com/mrrfv/linux-android-backup/blob/0fa07936f958801d027d29758a08235d8f9c6acd/README.md?plain=1#L81

2022-11-16 22:47 UTC, pvint commented
The changes you suggest make sense and look good - I'll try to do them tomorrow and re-test.

Paul

2024-01-28 13:02 UTC, kaktus40 commented
Hi, I'm very interested in disabled compression...

2024-01-28 19:56 UTC, mrrfv commented
@kaktus40 You can use the `discouraged_disable_archive` environment variable if you really need to disable compression and encryption, see [here](https://github.com/mrrfv/open-android-backup#automationunattended-backups) for details.

2024-02-23 18:54 UTC, 3eggert commented
perhaps my pr:  

make compression level adjustable #105 

can help since this one seems abandoned.

2024-04-02 14:34 UTC, closed without merging